[multi-module] 모듈명에 맞게 패키지를 변경하자 FileNotFoundException 발생
Caused by: java.io.FileNotFoundException: class path resource [til/example/multimodulelabs/user/application/UserRepository.class] cannot be opened because it does not exist
	at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:215) ~[spring-core-6.1.10.jar:6.1.10]

	org.springframework.beans.factory.BeanDefinitionStoreException: I/O failure while processing configuration class [til.example.multimodulelabs.user.UserEntityRepository]